### ISSUE TITLE
Browser Search Integration

### ISSUE THREAD

**Issue by aadityabhatia** [trackawesomelist/trackawesomelist-source#10]
Would love to add trackawesomelist.com as a search option in my browser. This enables [search engine shortcuts](https://support.mozilla.org/en-US/kb/assign-shortcuts-search-engines). I understand that search is done on the client side, but it should not make a difference.

To implement this feature, just need to support query strings in some way, e.g.
- https://www.trackawesomelist.com/search/?q=AWESOME
- https://www.trackawesomelist.com/search/AWESOME

Additionally, the [Mycroft Project](https://mycroftproject.com/) offers search engine plugins. Adding trackawesomelist.com to that list will increase discoverability and usefulness of this awesome collection!

**Comment by theowenyoung** [comment]
Hi, thanks for this excellent suggestion, the latest version has supported the q parameter, which you can now access:

https://www.trackawesomelist.com/search/?q=AWESOME
